import { Story } from './db';
import { CATEGORIES, Category } from './constants';

const getCat = (name: string): Category => {
  const found = CATEGORIES.find(c => c.name === name);
  return found || { id: Math.random().toString(), name };
};

export const MOCK_STORIES: Story[] = [
  {
    id: "mock-1",
    title: "Hành Trình Xuyên Không",
    author: "Nguyễn Nhật Ánh",
    synopsis: "Một câu chuyện ly kỳ về chuyến du hành thời gian về triều đại nhà Lê.",
    coverUrl: "https://picsum.photos/seed/story1/400/600",
    categories: [getCat("Xuyên Không"), getCat("Huyền Huyễn")],
    status: "Đang ra",
    chapterCount: 45,
    views: 12500,
    rating: 4.8,
    ratingCount: 120,
    uploaderId: "system",
    createdAt: new Date().toISOString() as any,
    updatedAt: new Date().toISOString() as any
  },
  {
    id: "mock-2",
    title: "Mưa Dừng Sau Mái Ngói",
    author: "Nam Cao",
    synopsis: "Tình yêu nhẹ nhàng chớm nở giữa những ngày mưa rào Hà Nội.",
    coverUrl: "https://picsum.photos/seed/story2/400/600",
    categories: [getCat("Ngôn Tình"), getCat("Đô Thị")],
    status: "Hoàn thành",
    chapterCount: 20,
    views: 8900,
    rating: 4.5,
    ratingCount: 85,
    uploaderId: "system",
    createdAt: new Date().toISOString() as any,
    updatedAt: new Date().toISOString() as any
  },
  {
    id: "mock-3",
    title: "Bạch Công Tử và Hắc Công Tử",
    author: "Ngô Tất Tố",
    synopsis: "Cuộc đối đầu huyền thoại giữa hai thái cực trong giới võ lâm.",
    coverUrl: "https://picsum.photos/seed/story3/400/600",
    categories: [getCat("Kiếm Hiệp"), getCat("Võng Du")],
    status: "Hoàn thành",
    chapterCount: 150,
    views: 45000,
    rating: 4.9,
    ratingCount: 500,
    uploaderId: "system",
    createdAt: new Date().toISOString() as any,
    updatedAt: new Date().toISOString() as any
  },
  {
    id: "mock-4",
    title: "Lời Nguyền Của Rồng",
    author: "Tô Hoài",
    synopsis: "Sứ mệnh giải cứu vương quốc khỏi bóng tối ngàn năm.",
    coverUrl: "https://picsum.photos/seed/story4/400/600",
    categories: [getCat("Kỳ Huyễn"), getCat("Phiêu Lưu")],
    status: "Đang ra",
    chapterCount: 62,
    views: 3200,
    rating: 4.2,
    ratingCount: 40,
    uploaderId: "system",
    createdAt: new Date().toISOString() as any,
    updatedAt: new Date().toISOString() as any
  },
  {
    id: "mock-5",
    title: "Mắt Biếc",
    author: "Nguyễn Nhật Ánh",
    synopsis: "Tình yêu đơn phương đầy tiếc nuối của Ngạn dành cho Hà Lan.",
    coverUrl: "https://picsum.photos/seed/story5/400/600",
    categories: [getCat("Vườn Trường")],
    status: "Hoàn thành",
    chapterCount: 12,
    views: 105000,
    rating: 5.0,
    ratingCount: 2400,
    uploaderId: "system",
    createdAt: new Date().toISOString() as any,
    updatedAt: new Date().toISOString() as any
  },
  {
    id: "mock-6",
    title: "Dế Mèn Phiêu Lưu Ký",
    author: "Tô Hoài",
    synopsis: "Những chuyến phiêu lưu kỳ thú của chú Dế Mèn dũng cảm.",
    coverUrl: "https://picsum.photos/seed/story6/400/600",
    categories: [getCat("Huyền Huyễn")],
    status: "Hoàn thành",
    chapterCount: 10,
    views: 75000,
    rating: 4.9,
    ratingCount: 1500,
    uploaderId: "system",
    createdAt: new Date().toISOString() as any,
    updatedAt: new Date().toISOString() as any
  },
  {
    id: "mock-7",
    title: "Số Đỏ",
    author: "Vũ Trọng Phụng",
    synopsis: "Sự thăng tiến bi hài của Xuân Tóc Đỏ trong xã hội cũ.",
    coverUrl: "https://picsum.photos/seed/story7/400/600",
    categories: [getCat("Đô Thị")],
    status: "Hoàn thành",
    chapterCount: 20,
    views: 54000,
    rating: 4.7,
    ratingCount: 890,
    uploaderId: "system",
    createdAt: new Date().toISOString() as any,
    updatedAt: new Date().toISOString() as any
  },
  {
    id: "mock-8",
    title: "Lão Hạc",
    author: "Nam Cao",
    synopsis: "Nỗi đau và lòng tự trọng của một lão nông nghèo.",
    coverUrl: "https://picsum.photos/seed/story8/400/600",
    categories: [getCat("Hiện Đại")],
    status: "Hoàn thành",
    chapterCount: 1,
    views: 32000,
    rating: 4.9,
    ratingCount: 1200,
    uploaderId: "system",
    createdAt: new Date().toISOString() as any,
    updatedAt: new Date().toISOString() as any
  },
  {
    id: "mock-9",
    title: "Tắt Đèn",
    author: "Ngô Tất Tố",
    synopsis: "Cuộc đời khốn khổ của Chị Dậu dưới ách áp bức.",
    coverUrl: "https://picsum.photos/seed/story9/400/600",
    categories: [getCat("Hiện Đại")],
    status: "Hoàn thành",
    chapterCount: 15,
    views: 41000,
    rating: 4.8,
    ratingCount: 950,
    uploaderId: "system",
    createdAt: new Date().toISOString() as any,
    updatedAt: new Date().toISOString() as any
  },
  {
    id: "mock-10",
    title: "Những Ngày Thơ Ấu",
    author: "Nguyên Hồng",
    synopsis: "Hồi ký về tuổi thơ đầy cay đắng nhưng ấm áp tình mẫu tử.",
    coverUrl: "https://picsum.photos/seed/story10/400/600",
    categories: [getCat("Hiện Đại")],
    status: "Hoàn thành",
    chapterCount: 9,
    views: 28000,
    rating: 4.6,
    ratingCount: 430,
    uploaderId: "system",
    createdAt: new Date().toISOString() as any,
    updatedAt: new Date().toISOString() as any
  },
  {
    id: "mock-11",
    title: "Nỗi Buồn Chiến Tranh",
    author: "Bảo Ninh",
    synopsis: "Những ký ức ám ảnh và bi thương về cuộc chiến.",
    coverUrl: "https://picsum.photos/seed/story11/400/600",
    categories: [getCat("Hiện Đại")],
    status: "Hoàn thành",
    chapterCount: 1,
    views: 62000,
    rating: 5.0,
    ratingCount: 1800,
    uploaderId: "system",
    createdAt: new Date().toISOString() as any,
    updatedAt: new Date().toISOString() as any
  },
  {
    id: "mock-12",
    title: "Bến Không Chồng",
    author: "Dương Hướng",
    synopsis: "Cuộc sống của những người phụ nữ làng quê sau chiến tranh.",
    coverUrl: "https://picsum.photos/seed/story12/400/600",
    categories: [getCat("Hiện Đại")],
    status: "Hoàn thành",
    chapterCount: 25,
    views: 18000,
    rating: 4.4,
    ratingCount: 210,
    uploaderId: "system",
    createdAt: new Date().toISOString() as any,
    updatedAt: new Date().toISOString() as any
  },
  {
    id: "mock-13",
    title: "Chiếc Lược Ngà",
    author: "Nguyễn Quang Sáng",
    synopsis: "Tình cha con sâu nặng trong khói lửa chiến tranh.",
    coverUrl: "https://picsum.photos/seed/story13/400/600",
    categories: [getCat("Hiện Đại")],
    status: "Hoàn thành",
    chapterCount: 1,
    views: 45000,
    rating: 4.9,
    ratingCount: 1300,
    uploaderId: "system",
    createdAt: new Date().toISOString() as any,
    updatedAt: new Date().toISOString() as any
  },
  {
    id: "mock-14",
    title: "Mùa Lá Rụng Trong Vườn",
    author: "Ma Văn Kháng",
    synopsis: "Sự thay đổi của một gia đình Hà Nội trong thời kỳ đổi mới.",
    coverUrl: "https://picsum.photos/seed/story14/400/600",
    categories: [getCat("Đô Thị")],
    status: "Hoàn thành",
    chapterCount: 30,
    views: 22000,
    rating: 4.5,
    ratingCount: 340,
    uploaderId: "system",
    createdAt: new Date().toISOString() as any,
    updatedAt: new Date().toISOString() as any
  },
  {
    id: "mock-15",
    title: "Truyện Kiều",
    author: "Nguyễn Du",
    synopsis: "Tác phẩm kinh điển về cuộc đời nàng Thúy Kiều.",
    coverUrl: "https://picsum.photos/seed/story15/400/600",
    categories: [getCat("Cổ Đại")],
    status: "Hoàn thành",
    chapterCount: 3254,
    views: 500000,
    rating: 5.0,
    ratingCount: 10000,
    uploaderId: "system",
    createdAt: new Date().toISOString() as any,
    updatedAt: new Date().toISOString() as any
  },
  {
    id: "mock-16",
    title: "Hồn Trương Ba, Da Hàng Thịt",
    author: "Lưu Quang Vũ",
    synopsis: "Bi kịch về sự không thống nhất giữa bên trong và bên ngoài.",
    coverUrl: "https://picsum.photos/seed/story16/400/600",
    categories: [getCat("Huyền Huyễn")],
    status: "Hoàn thành",
    chapterCount: 3,
    views: 35000,
    rating: 4.9,
    ratingCount: 780,
    uploaderId: "system",
    createdAt: new Date().toISOString() as any,
    updatedAt: new Date().toISOString() as any
  },
  {
    id: "mock-17",
    title: "Lục Vân Tiên",
    author: "Nguyễn Đình Chiểu",
    synopsis: "Ca ngợi đạo nghĩa làm người và lòng trung nghĩa.",
    coverUrl: "https://picsum.photos/seed/story17/400/600",
    categories: [getCat("Cổ Đại")],
    status: "Hoàn thành",
    chapterCount: 2082,
    views: 120000,
    rating: 4.8,
    ratingCount: 2100,
    uploaderId: "system",
    createdAt: new Date().toISOString() as any,
    updatedAt: new Date().toISOString() as any
  },
  {
    id: "mock-18",
    title: "Chuyện Con Mèo Dạy Hải Âu Bay",
    author: "Luis Sepúlveda",
    synopsis: "Câu chuyện cảm động về tình yêu và lời hứa.",
    coverUrl: "https://picsum.photos/seed/story18/400/600",
    categories: [getCat("Sủng Văn")],
    status: "Hoàn thành",
    chapterCount: 11,
    views: 98000,
    rating: 5.0,
    ratingCount: 3500,
    uploaderId: "system",
    createdAt: new Date().toISOString() as any,
    updatedAt: new Date().toISOString() as any
  },
  {
    id: "mock-19",
    title: "Cô Gái Đến Từ Hôm Qua",
    author: "Nguyễn Nhật Ánh",
    synopsis: "Kỷ niệm tuổi thơ và tình yêu tuổi học trò ngọt ngào.",
    coverUrl: "https://picsum.photos/seed/story19/400/600",
    categories: [getCat("Vườn Trường")],
    status: "Hoàn thành",
    chapterCount: 15,
    views: 67000,
    rating: 4.7,
    ratingCount: 1200,
    uploaderId: "system",
    createdAt: new Date().toISOString() as any,
    updatedAt: new Date().toISOString() as any
  },
  {
    id: "mock-20",
    title: "Bước Qua Lời Nguyền",
    author: "Tạ Duy Anh",
    synopsis: "Sự đấu tranh để vượt qua những hận thù cũ của thế hệ trước.",
    coverUrl: "https://picsum.photos/seed/story20/400/600",
    categories: [getCat("Ngược Văn")],
    status: "Hoàn thành",
    chapterCount: 1,
    views: 15000,
    rating: 4.3,
    ratingCount: 180,
    uploaderId: "system",
    createdAt: new Date().toISOString() as any,
    updatedAt: new Date().toISOString() as any
  }
];

