export interface Category {
  id: string;
  name: string;
}

export const CATEGORIES: Category[] = [
  { id: '1', name: 'Ngôn Tình' },
  { id: '2', name: 'Ngôn Tình 🔞' },
  { id: '3', name: 'Đam Mỹ' },
  { id: '4', name: 'Đam Mỹ 🔞' },
  { id: '8', name: 'Kiếm Hiệp' },
  { id: '9', name: 'Xuyên Không' },
  { id: '10', name: 'Xuyên Nhanh' },
  { id: '11', name: 'Huyền Huyễn' },
  { id: '12', name: 'Kỳ Huyễn' },
  { id: '13', name: 'Khoa Huyễn' },
  { id: '14', name: 'Võng Du' },
  { id: '15', name: 'Đô Thị' },
  { id: '16', name: 'Đồng Nhân' },
  { id: '17', name: 'Dị Năng' },
  { id: '18', name: 'Mạt Thế' },
  { id: '19', name: 'Cổ Đại' },
  { id: '20', name: 'Hiện Đại' },
  { id: '21', name: 'Tương Lai' },
  { id: '22', name: 'Tinh Tế' },
  { id: '23', name: 'Trọng Sinh' },
  { id: '24', name: 'Hệ Thống' },
  { id: '25', name: 'Sảng Văn' },
  { id: '26', name: 'Sủng Văn' },
  { id: '27', name: 'Ngược Văn' },
  { id: '28', name: 'HE' },
  { id: '29', name: 'SE' },
  { id: '30', name: 'OE' },
  { id: '31', name: 'GE' },
  { id: '32', name: 'BE' },
  { id: '33', name: 'Bệnh Kiều' },
  { id: '34', name: 'Chiếm Hữu' },
  { id: '35', name: 'Trung Khuyển' },
  { id: '36', name: 'Đoàn Sủng' },
  { id: '37', name: 'Cố Chấp' },
  { id: '38', name: 'Nhân Thú' },
  { id: '39', name: 'ABO' },
  { id: '40', name: 'Đại Lão' },
  { id: '41', name: 'Vườn Trường' },
  { id: '42', name: 'Giới Giải Trí' },
  { id: '43', name: 'Linh Dị' },
  { id: '44', name: 'Trinh Thám' },
  { id: '45', name: 'Kinh Dị' },
];
